# Syllabus {-}

**Course:** ENST/MRNE 392 Field Research Methods Fall 2024  
**Lecture:** Tues & Thurs 8:30 - 9:45 Schaefer 111  
**Lab:** Thurs 1:10-4:30 Schaefer 112 <br />
**Instructor:** Dr. Cassie Gurbisz  (you can call me Cassie) <br />
**Email:** cbgurbisz@smcm.edu <br />
**Office hours:** Tuesdays 12:00-2:00 Kent Hall 308 <br /> 
**Website:** https://MRNE392.github.io/website/

## Course description {-}
In this course, you will learn methods of sampling and analyzing the natural environment. An emphasis will be placed on research question formulation and sampling design. By the end of the course, students will be able to independently develop a field study, collect and analyze field data, and present their findings in a poster presentation. We will focus on our local estuarine environment, although the general research process covered can be applied to any system.

## Course materials {-}
All of the readings in this class are either free or will be provided by the instructor.

## Learning outcomes {-}
At the completion of this course, students will be able to design and conduct ecological field investigations using proper scientific methods.

Specific outcomes include being able to:

* Formulate and articulate hypotheses or questions about observed ecological phenomena 
* Develop and articulate an appropriate field study design to test hypotheses or address research questions
* Use appropriate methods to collect ecological field data
* Record and manage detailed ecological data, including field procedures, site observations and quantitative field measurements
* Analyze observational and experimental field data and report results in the form of a conference-style poster presentation
* Collaborate effectively with a diverse team of researchers and learners

## Working outside {-}
This course involves a lot of outdoor work. Sometimes the weather will be beautiful, but more often it will be hot, sunny, buggy, cold, wet, windy, or a combination of these uncomfortable conditions. We will go out rain or shine unless the conditions are unsafe. It is important that you come to class prepared with whatever you need to keep yourself safe and comfortable outside. It's always a good idea to have a hat and sunscreen and a waterproof layer, even if rain is not in the forecast. For boat work, it is almost always much cooler on the water than land, so come prepared with multiple layers. Closed-toe shoes are required on the boat. Crocs or sneakers are fine in warm weather. Rubber boots are ideal in cooler weather but sneakers or anything with a grippy rubber sole are fine too. Do not wear flip-flops, heels, or nice shoes that can't get wet or that could scuff up the boat deck. 

I recommend investing in good rain gear, especially if you plan to continue doing fieldwork on the water beyond this class. [Grundens](https://grundens.com/) is a reputable marine work gear supplier and they have some affordable options. [Outdoor Research](https://www.outdoorresearch.com/) also sells high-quality gear and you can apply for a [student discount](https://www.outdoorresearch.com/pages/vip-program?gad_source=1&gclid=Cj0KCQjwkdO0BhDxARIsANkNcrfTTRmTvBF6i9f4siwcZSvr-3FYPgDXYPUw5zkBXpXfyFCTJc8cJKAaAtSCEALw_wcB).

## Grading and assessment {-}

This course uses a variation of "specifications grading," where we rely less on evaluating every assignment with a letter or number and instead focus on making sure we're generally making good progress in our learning. [Research has shown](https://www.alfiekohn.org/article/case-grades/) that grading doesn't improve learning and can sometimes even harm learning. Rather than submitting work "in exchange" for a letter or number grade, most assignments will be evaluated based on whether or not they meet the "specifications," or "specs" of that particular assignment. If the specs are not met, you'll often have the opportunity to revise your assignment until the specs are met so that you have more than one chance to demonstrate your learning. Your final grade will be based on the number of assignments for which you meet the specs and, therefore, demonstrate your mastery of the course topics. With this approach to evaluation, the goal is to emphasize truly becoming an expert in the course content. 

The following outlines the grading system:

* **A** Meet specs on: at least 9/10 quizzes, 3/3 lab reports, and poster
* **B** Meet specs on: at least 8/10 quizzes, 2/3 lab reports, and poster
* **C** Meet specs on: at least 7/10 quizzes, 2/3 lab reports, and poster
* **D** Meet specs on: at least 6/10 quizzes, 1/3 lab reports, and poster 
* **F** Does not meet one or more of the requirements to earn a D, and/or student has 6 or more unexplained absences 

**Quizzes**

Weekly-ish assessments will take the form of quizzes. They are designed to 1) help the instructor monitor how well you’re learning, 2) help you monitor your own learning and make adjustments to improve, and 3) encourage you to study course material outside of class. However, I don't want the quizzes to be an source of anxiety for you, so we're using a different form of grading to evaluate your work. First you'll take the quiz individually in class. You'll then confer with your peers to discuss your responses. At this stage, you can also use any of your hand-written notes as a reference. You'll then modify your responses and finally reflect on any questions you missed. This encourages you to think about misconceptions your may have had and consider how you might improve your study habits. The quizzes are graded as "meets specs/does not meet specs." In order to meet the specifications, you need to earn a minimum number of points on the individual and group portions of the quiz (typically 70% individual, 100% group/open notes). Meeting specs also requires that you write a brief but thoughtful reflection on your learning. The only quizzes that will not include peer discussion and revision are the species ID and knot-tying quizzes.

Quizzes can be made up during the instructor's office hours or by appointment, but note that you will not be able to confer with your peers. Missed quizzes must be made up within 2 weeks of the missed quiz date.

My aim is to be completely transparent about what content will be assessed in the quizzes. Each day's "topic and materials" page will contain a list of the learning objectives for that day. Unless otherwise noted, quizzes will generally assess the learning objectives covered since the last previous quiz. Use these learning objectives as a study guide as you review the slides and readings. You may want to make a concise "cheat-sheet" from your notes to bring on the day of each quiz. Since open notes are permitted, this will help you quickly find information for each learning objective. Making cheat-sheets also helps you study!

**Lab reports**

At the conclusion of each of our three field studies, you'll write a brief lab report to communicate your results and demonstrate your understanding of the field research process. Specifications for each report will be provided. If your report does not meet specifications, you will have the opportunity to revise it until it does meet specs. Revised lab reports must be submitted within one week of receiving instructor feedback.

**Poster**

At the end of the course, you'll choose one of our field studies to present at the SMCM fall student poster symposium. The goal of the poster assignment is to demonstrate that you have an in-depth understanding of how we developed our research question, hypothesis, methods, and results for the field study. As with the lab reports, you will have the opportunity to revise the poster until it meets specs or until the poster printing deadline. Posters that do not meet specs will not qualify for presenting at the public poster symposium. 

**Unexplained absences**

I define an unexplained absence as missing class without notifying the professor (in other words, “ghosting” the class). As long as you let the instructor know you won’t be able to make it to class, an absence is considered “explained,” no doctor’s note or other official documentation needed. Please don’t come to class if you are sick! Just be sure to keep me in the loop via a quick email.

On the flip side, please consider the consequences of missing class meetings – this is a hands-on course where most of the learning takes place in person. It will be hard to learn and, therefore, pass the class if you’re not here to participate. This is why attendance is included in the specs for earning an F in the class. If we are not in close communication about your absences, catching up on more than a couple days of missed work will not be possible. 

If you need to miss class, please don't ask me what you missed - it's all in the class schedule. You should review and take notes on whatever slides and readings are listed under the topics and materials for that day.

**Extra credit**

The specs grading system is designed to reduce anxiety over grades, but I recognize that you still may experience some stress over the quizzes and assignments, especially if you are just below the benchmark for a particular course grade or you would like the opportunity to earn a "plus" grade. I will offer multiple opportunities that will enable you to earn one extra credit point, which you can use as a "free pass" to automatically meet specs on one quiz or add a "plus" to your grade. So if, for example, if you only meet the specs on 8 quizzes but you need to pass 9 to earn a B and you meet all of the other B requirements, you can use your extra credit point to automatically pass your missing quiz and, therefore, earn a B in the class. Or if you met all of the requirements for a B, but you'd really like to earn a B+, you can use your extra credit point to add a "+" to your final grade. There are no "-" final grades in this class. I will notify you of extra credit opportunities as soon as they arise.

## More policies {-}

**Late work**

I encourage you to stick to assignment deadlines - they exist to keep you on track so you don't fall behind with coursework. However, I am also flexible if you really need an extra day or two to complete an assignment. Just ask - it's usually not a problem. You should think about the purpose of a particular due date and how a late submission will affect your learning. A late submission might mean you will miss the opportunity to get feedback on your work, or you might miss the chance to work collaboratively with your peers. You should take these learning opportunities into consideration before requesting an extension.

**Use of AI**

The use of generative AI within lab reports and the poster assignment is not allowed. If you try to use AI for this work, it will probably generate nonsensical word vomit, anyway, since the assignments in this class are based on our own original research and not outside information sources (see this [scholarly article](https://link.springer.com/article/10.1007/s10676-024-09775-5) for details). If I suspect that you have used AI to create your assignments, you can expect to have a conversation with me!

You might consider using AI to help you develop study guides. However, your quiz notes must still be hand-written.

**Engaged learning**

SMCM has recently decreased the amount of time allocated to class meetings. In order to maintain the depth of learning that is required for a 4-credit course, some of your learning will take place by engaging with class material outside of normal lecture hours. Because the course includes a lab period, most of our "engaged learning" will take place via hands-on activities during lab.  

**Office hours**

Office hours are set times dedicated to students. This means that I will be in my office waiting for you to come by talk to me during that time!

## SMCM resources {-}

**Accommodations and Accessibility:** SMCM is committed to providing access to the learning and living experience to students with disabilities and disabling health conditions. If you have received a letter from the Office of Accessibility Services (OAS), which outlines the academic accommodations to which you are entitled to and you want  those accommodations to apply to this course, you MUST share your letter and meet with me to review that letter. If you suspect that you have a learning or living need related to a disability or disabling health condition that could benefit from  accommodations, you should contact the Office of Accessibility Services, who can help you learn more about how to proceed. Email: adasupport@smcm.edu

**Office of Student Success Services:** The Office of Student Success Services (OS3) connects students to the resources, activities, services, and programs that can help students be successful, thrive, and persist to graduation. OS3 provides free tutoring services and academic coaching (strategies for time management, getting organized, overcoming procrastination, note-taking, test-taking, study skills, sleep and stress management, etc.) with professional staff and Peer Academic Success Strategies (PASS) Specialists. You may make appointments by emailing PASS@smcm.edu. To request tutoring for a specific course, email tutoring@smcm.edu. For any other help call 240-895-4388, stop by Glendening 230, or email os3@smcm.edu. Asking for help is an important skill to learn. Students who seek assistance and use the resources we have on campus tend to do better academically, socially, and emotionally than the students who do not ask for help or use the resources. Let us provide assistance and support when you need it.

**The Writing and Speaking Center:** Located on the first floor of the main Library, the Writing & Speaking Center offers free peer tutoring in writing and speaking. The peer tutors are students themselves, but they have completed extensive hands-on training to learn how to assist their peers at any step of the process (planning, drafting, or revising) for any writing or speaking assignment. The peer tutors will not make decisions about revision for you and will instead work collaboratively with you to discuss ideas and consider options so that you can choose how best to revise on your own. This collaborative approach is one of the best ways to help students develop their abilities because all writers and speakers need audiences—just ask the peer tutors, who often schedule tutorials with each other. To make an appointment, please visit www.smcm.edu/writingcenter and click the “Schedule an Appointment” button. If you have questions or need assistance, please contact Interim Director Amanda Taylor at apheatwole@smcm.edu.

**Office of Title IX Compliance and Training:** St. Mary's College of Maryland is committed to helping create a safe and open learning environment for all students. If you (or someone you know) have experienced any form of Sex Discrimination, know that help and support are available. Sex Discrimination means exclusion from participation in or being denied the benefits of any education program or activity on the basis of sex, including sex stereotypes, sex characteristics, sexual orientation, gender identity, and pregnancy or related conditions. Sex-Based Harassment is a form of Sex Discrimination that includes the following types of conduct: quid pro quo harassment, hostile environment harassment, sexual assault, dating violence, domestic violence, and stalking.  
 
The College strongly encourages all community members to take action, seek support, and report incidents of Sex Discrimination to the Title IX Office.  Under Title IX of the Education Amendments of 1972, I am required to disclose information about such Sex Discrimination to the Title IX Office.
If you would like to talk to a confidential employee who does not have this reporting responsibility, you can contact SMCM Wellness Center (240) 895-4289. 

For more information about reporting options and resources at St. Mary's College of Maryland and the community, please visit the Office of Title IX Compliance and Training.

**Wellness Center:** A growing number of students are experiencing mental health challenges to varying degrees. Doing what you can to stay ahead by wisely taking care of yourself will be a key to succeeding academically.  Sometimes mental health challenges can affect your ability to complete required work. For example, a particular assignment might trigger anxiety for you in ways which were not anticipated. Or, maybe it becomes difficult to attend class due to mental health challenges. In any of those cases please come and talk with more or send me an email.  I’ll listen and do what I can to help. The sooner you share your challenges with me, the better prepared I am to assist you.  I am one of many people here at SMCM who care about you and your welfare. For further support, the Wellness Center provides numerous confidential health and counseling services including same day/next day connections to counseling by calling 240-895-4289 or emailing the Director at jljolly@smcm.edu

